name: athletes-pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - mlflow
    - pandas
    - scikit-learn
    - feast
    - codecarbon
    - seaborn
    - matplotlib
    - numpy